# Generated by Django 4.2.13 on 2024-07-17 17:49

from django.db import migrations, models
import django.db.models.deletion
import invias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method_Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to=invias.models.pending_directory_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('method_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invias.method_publication')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_description', models.TextField()),
                ('path', models.FileField(blank=True, null=True, upload_to=invias.models.store_directory_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invias.pending')),
            ],
        ),
    ]
