# Generated by Django 4.2.13 on 2024-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method_publication',
            name='verification_date',
            field=models.DateTimeField(null=True),
        ),
    ]
