# Generated by Django 4.2.13 on 2024-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invias', '0002_method_publication_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='method_publication',
            name='last_process',
            field=models.DateTimeField(null=True),
        ),
    ]
