"""
Django settings for invias project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z!d4)$_^*n6gwxt34ubn-$+6d6#eng4-n4v2$-%l+hy0_76cv4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '34.28.128.104']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'invias',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invias.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invias.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# LOCAL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'invias',
        'HOST': 'localhost',
        'USER': 'postgres',
        'PASSWORD': 'saroa',
    }
}

# # SERVER
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'HOST': '34.123.92.206',
#         'USER': 'postgres',
#         'PASSWORD': 'O_#>g[42Ba54z~{7',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
DATA TEMPORAL
"""

POSTGRES_USER="this is part of the dotenv"
# lifetime of stored publications (days)
ENV_PUB_LIFETIME=1
# interval of time to send a request to open the session (minutes)
ENV_REQUEST_TIME=3
# Identifier
ENV_COUNTRY_CODE='CO'
ENV_NATIONAL_IDENTIFIER='INVIA'
# Server URL
ENV_SERVER_URL = 'https://datex2-sinitt.mintransporte.gov.co/v3.1'

# Keep-alive Execution time
ENV_KEEP_ALIVE_MINUTES=1
#time zone 
ENV_TIMEZONE = "America/Bogota"
#Maximun size per translation
ENV_MAX_SIZE= 10485760
#path of mapping file to sitetable 
ENV_MAPPING_PATH="translator/mapping.json"

ENV_PROCESS_AMOUNT = 2
ENV_PROCESS_TIME_SECONDS = 5

# Encoding
ENCODING ='latin-1'
ENCODING_2 ='UTF-8'
UNSENT_PUB_DIR = "store"
PENDING_PUB_DIR = "pending"
UNSENT_PUB_PATH = UNSENT_PUB_DIR + '/pending_publications.json' #.format(datetime.today().date())

TOKEN_ERROR = "asdfghj"

ELASTIC_URL = "http://20.99.184.101"
ELASTIC_USER = "elastic"
ELASTIC_PASS = "Colombia1234$"

"""
ENDPOINTS
"""
# PUBLICATION TYPES
MEASURED_DATA_PUBLICATION = "measuredDataPublication"
ELABORATED_DATA_PUBLICATION = "elaboratedDataPublication"
SITUATION_PUBLICATION = "situationPublication"
MEASURED_SITE_TABLE_PUBLICATION = "MeasuredSiteTablePublication"
VMS_PUBLICATION = "vmsPublication"
VMS_TABLE_PUBLICATION = "vmsTablePublication"

OPEN_SESSION_PATH = '/openSession'
PUT_DATA_PATH = '/putData'
PUT_SNAPSHOT_DATA_PATH = '/putSnapShotData'
CLOSE_SESSION_PATH = '/closeSession'
KEEP_ALIVE_PATH = '/keepAlive'

# Test parameters
FAKE_API_KEY = 'fake_api_key'